require_relative 'wc_metadata_api/client'
require_relative 'wc_metadata_api/helper'
require_relative 'oclc/auth'
require_relative 'clop/clop'
require 'nokogiri'
require 'uri'
require 'net/http'
require 'cgi'
require 'yaml'

